export APP_JLMRT_PEBBLE_PROXY_API_HOST="jlmrt-pebble-proxy_api_1"
export APP_JLMRT_PEBBLE_PROXY_API_PORT="8080"
export APP_JLMRT_PEBBLE_PROXY_API_URL="http://${APP_JLMRT_PEBBLE_PROXY_API_HOST}:${APP_JLMRT_PEBBLE_PROXY_API_PORT}"
